# Generated by Django 4.1.3 on 2022-11-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
